error: defined an event without a `Reflect` implementation
  --> tests/ui/missing_reflect/impl.rs:42:1
   |
42 | struct MyEvent(String);
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
note: `Event` implemented here
  --> tests/ui/missing_reflect/impl.rs:45:1
   |
45 | / impl Event for MyEvent {
46 | |     type Trigger<'a> = GlobalTrigger;
47 | | }
   | |_^
note: the lint level is defined here
  --> tests/ui/missing_reflect/impl.rs:8:9
   |
 8 | #![deny(bevy::missing_reflect)]
   |         ^^^^^^^^^^^^^^^^^^^^^
help: `Reflect` can be automatically derived
   |
42 + #[derive(Reflect)]
43 | struct MyEvent(String);
   |

error: defined a message without a `Reflect` implementation
  --> tests/ui/missing_reflect/impl.rs:51:1
   |
51 | struct MyMessage(String);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: `Message` implemented here
  --> tests/ui/missing_reflect/impl.rs:54:1
   |
54 | impl Message for MyMessage {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: `Reflect` can be automatically derived
   |
51 + #[derive(Reflect)]
52 | struct MyMessage(String);
   |

error: defined a component without a `Reflect` implementation
  --> tests/ui/missing_reflect/impl.rs:22:1
   |
22 | struct MyComponent;
   | ^^^^^^^^^^^^^^^^^^^
   |
note: `Component` implemented here
  --> tests/ui/missing_reflect/impl.rs:25:1
   |
25 | / impl Component for MyComponent {
26 | |     const STORAGE_TYPE: StorageType = StorageType::Table;
27 | |     type Mutability = Mutable;
28 | | }
   | |_^
help: `Reflect` can be automatically derived
   |
22 + #[derive(Reflect)]
23 | struct MyComponent;
   |

error: defined a resource without a `Reflect` implementation
  --> tests/ui/missing_reflect/impl.rs:32:1
   |
32 | / struct MyResource {
33 | |     field_1: usize,
34 | |     field_2: bool,
35 | | }
   | |_^
   |
note: `Resource` implemented here
  --> tests/ui/missing_reflect/impl.rs:38:1
   |
38 | impl Resource for MyResource {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: `Reflect` can be automatically derived
   |
32 + #[derive(Reflect)]
33 | struct MyResource {
   |

error: aborting due to 4 previous errors

